import Head from 'next/head'
import { Main } from '../styles/sharedstyles'
import { 
  Buttons, 
  Products, 
  Shirts, 
  Mugs, 
  Categories
} from '../styles/home'
import { useState } from 'react'
import Pages from '../components/Pages'
import Image from 'next/image'
import arrow from "../public/Arrows, Diagrams/Arrow.svg"

export default function Home() {
  const [menuSelect, setMenuSelect] = useState(1);

  return (
    <>
      <Head>
        <title>Capputeeno</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Buttons >
          <Products $primary={menuSelect}
          onClick={() => { setMenuSelect(1)}}>
            TODOS OS PRODUTOS</Products>

          <Shirts $primary={menuSelect}
          onClick={() => { setMenuSelect(2)}}>
            CAMISETAS</Shirts>

          <Mugs $primary={menuSelect}
          onClick={() => { setMenuSelect(3)}}>
            CANECAS</Mugs>

        </Buttons>
        <Categories>
          <div>
            <h2>Organizar por</h2>
            <Image src={arrow} alt="button" />
          </div>

          <Pages />
        </Categories>
      </Main>
    </>
  )
}
