import Head from 'next/head'
import { Main } from '../styles/sharedstyles'
import { Feed } from '../styles/home'
import Buttons_ from '../components/Buttons'
import { baseProducts, shirtsCategory, mugsCategory } from '../provisoryApi'
import Product from '../components/Product'
import { useState } from 'react'

export default function Home() {
  const [menuSelect, setMenuSelect] = useState(1);

  return (
    <Main>
        <Head>
          <title>Capputeeno</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        
        <Buttons_ menuSelect={menuSelect} setMenuSelect={setMenuSelect} />

        <Feed>
          {
            menuSelect === 1 ? 
            baseProducts.map((value, index) => 
              <Product
                id={value.id} 
                image={value.image_url}
                title={value.name}
                price={value.price} 
                key={index}
                />
            ) : 
            menuSelect === 2 ?
            shirtsCategory.map((value, index) => 
              <Product
                id={value.id} 
                image={value.image_url}
                title={value.name}
                price={value.price}
                key={index} 
                />
            ) :
            mugsCategory.map((value, index) => 
            <Product
              id={value.id} 
              image={value.image_url}
              title={value.name}
              price={value.price}
              key={index} 
              />
          )
          }
        </Feed>
      </Main>
  )
}
